Name=input("Wie heißt die Person?")
Absender=input("Wie heißt der Absender?")
print(f"Hallo {Name}")
print("")
print("Mit dieser Emal möchte ich dich über meine neue Adresse informieren.")
print("Musterstraße 123")
print("12345 Musterhausen")
print("Viele Grüße")
print("")
print(f"{Absender}")